---

x-ubuntu-default-ansible-user: &ubuntu-default-ansible-user
  ansible_user: ansible-test

x-ubuntu-ansible-inventory: &ubuntu-ansible-inventory
  host_vars:
    #ubuntu-trusty:
    #  <<: *ubuntu-default-ansible-user
    ubuntu-xenial:
      <<: *ubuntu-default-ansible-user
    ubuntu-bionic:
      <<: *ubuntu-default-ansible-user
    ubuntu-focal:
      <<: *ubuntu-default-ansible-user

x-ubuntu-template: &ubuntu-template
  #name: ubuntu-trusty
  #dockerfile: '../tests/Dockerfile.ubuntu-trusty'
  #image: ubuntu-trusty:ansible
  override_command: false
  pre_build_image: true
  recreate: true
  tty: true
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"


# MOLECULE START
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_PROJECT_DIRECTORY}/..
  yamllint .
  ansible-lint
platforms:
  # - name: instance
  #   image: docker.io/pycontribs/centos:8
  #   pre_build_image: true
  - <<: *ubuntu-template
    name: ubuntu-xenial
    dockerfile: '../tests/Dockerfile.ubuntu-xenial'
    image: ubuntu-xenial:ansible
provisioner:
  name: ansible
  #inventory: *ubuntu-ansible-inventory
  options:
   vvv: True
  #playbooks:
  #  converge: converge.yml
  ansible_args:
    - --extra-vars=active_playbook=autocomplete
    #converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_ROLES_PATH: "../../"
    MOLECULE_NO_LOG: False
scenario:
  name: default
  destroy_sequence:
    - destroy
  test_sequence:
    #- lint
    #- destroy
    - syntax
    - create
    - converge
      # - idempotence
    - verify
    #- destroy
verifier:
  name: ansible
